"""CLI wrapper around apps/api/app/catalog_generator.py: generate new
starter-curriculum phrases for a language pack using a local Ollama model,
and (unless --dry-run) append the validated ones to
language_packs/<code>/curriculum/starter.json.

Prefer the human-in-the-loop flow in apps/web_pwa's Catalog tab if you want
to review each phrase individually before it's written -- that calls the
same underlying generate_candidate_phrases()/approve_catalog_phrases()
functions this CLI does, just with a UI in between. This CLI writes
everything that structurally validates in one shot (after your own read of
the printed candidates, if you don't pass --dry-run first), no per-item
approval step.

Why the underlying safety caveat still applies here too: BhashaVaani's
lesson generator (apps/api/app/lesson_generator.py) deliberately only ever
selects phrase/meaning pairs that already exist in the approved starter
catalog -- it never lets a model invent a translation that gets shown to a
learner. That's a safety feature (LLM outputs must be validated before
persistence, per CLAUDE.md's architecture rules), but it also means
"Generate plan" can never produce genuinely new phrases once a learner has
seen most/all of a small catalog (see .ai/known-issues.yaml,
BV-REPEAT-CATALOG-001). Growing the catalog with a model (this script) can
only be structurally validated (non-empty fields, no duplicates) -- it
CANNOT verify the generated native-script text is linguistically correct.
Spot-check output before trusting it the way the hand-authored catalog
entries are trusted.

Usage:
    apps/api/.api-venv/Scripts/python.exe tools/generate_catalog_phrases.py \
        --language kn --model gemma4:latest --count 10 --dry-run

    apps/api/.api-venv/Scripts/python.exe tools/generate_catalog_phrases.py \
        --language kn --model gemma4:latest --count 10
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "apps" / "api"))

from app.catalog_generator import CatalogGenerationError, approve_catalog_phrases, generate_candidate_phrases  # noqa: E402
from app.provider_gateway import ProviderGatewayError  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--language", required=True, help="Language code, e.g. kn or hi")
    parser.add_argument("--model", required=True, help="Ollama model tag, e.g. gemma4:latest")
    parser.add_argument("--count", type=int, default=10, help="How many new phrases to request")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated candidates without writing to starter.json",
    )
    args = parser.parse_args()

    print(f"Requesting {args.count} new phrases for '{args.language}' from Ollama model '{args.model}'...")

    try:
        result = generate_candidate_phrases(language_code=args.language, model=args.model, count=args.count)
    except (CatalogGenerationError, ProviderGatewayError) as error:
        diagnostics = getattr(error, "diagnostics", None)
        print(f"Generation failed: {error}", file=sys.stderr)
        if diagnostics:
            print(f"Diagnostics: {diagnostics}", file=sys.stderr)
        raise SystemExit(1)

    candidates = result["candidates"]
    if not candidates:
        print("No valid new phrases were produced (all were duplicates, malformed, or empty). Nothing written.")
        return

    print(f"\nGot {len(candidates)} candidate new phrase(s) for {result['language_name']}:\n")
    for item in candidates:
        print(f"  {item['phrase']}  ({item['native_script']})  -- {item['meaning']}")

    print(
        "\nReminder: native-script text above was generated by a local model and has NOT been "
        "linguistically verified. Spot-check it before trusting it the way the rest of the "
        "catalog is trusted.",
    )

    if args.dry_run:
        print("\n--dry-run set: not writing to starter.json.")
        return

    write_result = approve_catalog_phrases(language_code=args.language, approved_items=candidates)
    print(f"\nWrote {write_result['added']} new phrase(s); catalog now has {write_result['total']} total.")
    print("Run tools/validate_language_packs.py and restart the backend to pick up the change.")


if __name__ == "__main__":
    main()
